export const GET_TITLES = 'GET_TITLES';
export const GET_TITLE_DETAILS = 'GET_TITLE_DETAILS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_LOADING = 'SET_LOADING';
export const TITLES_ERROR = 'TITLES_ERROR';
export const TITLE_DETAILS_ERROR = 'TITLE_DETAILS_ERROR';
export const SEARCH_TITLES = 'SEARCH_TITLES';
